//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bolnica.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bolnica.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolnica &quot;Zdravo&quot; korporacije, Novi Sad.
        /// </summary>
        public static string BolnicaZdravoTxtBlock {
            get {
                return ResourceManager.GetString("BolnicaZdravoTxtBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolnička soba.
        /// </summary>
        public static string Bolnička_soba {
            get {
                return ResourceManager.GetString("Bolnička soba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolnička soba.
        /// </summary>
        public static string BolnickaSobaCombo {
            get {
                return ResourceManager.GetString("BolnickaSobaCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brisanje leka.
        /// </summary>
        public static string Brisanje_leka {
            get {
                return ResourceManager.GetString("Brisanje leka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brisanje opreme.
        /// </summary>
        public static string Brisanje_opreme {
            get {
                return ResourceManager.GetString("Brisanje opreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brisanje sastojka.
        /// </summary>
        public static string Brisanje_sastojka {
            get {
                return ResourceManager.GetString("Brisanje sastojka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj prostorija:.
        /// </summary>
        public static string BrojProstorijaLabel {
            get {
                return ResourceManager.GetString("BrojProstorijaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BROJ PROSTORIJE.
        /// </summary>
        public static string BrojProstorijeDataGrid {
            get {
                return ResourceManager.GetString("BrojProstorijeDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj prostorije:.
        /// </summary>
        public static string BrojProstorijeLabel {
            get {
                return ResourceManager.GetString("BrojProstorijeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DODAJ.
        /// </summary>
        public static string btnDodaj {
            get {
                return ResourceManager.GetString("btnDodaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DODAJ NOVI.
        /// </summary>
        public static string btnDodajNovi {
            get {
                return ResourceManager.GetString("btnDodajNovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBRŠI.
        /// </summary>
        public static string btnObrisi {
            get {
                return ResourceManager.GetString("btnObrisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string btnOdustani {
            get {
                return ResourceManager.GetString("btnOdustani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNESI.
        /// </summary>
        public static string btnPodeli {
            get {
                return ResourceManager.GetString("btnPodeli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string btnPotvrdi {
            get {
                return ResourceManager.GetString("btnPotvrdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skladišti.
        /// </summary>
        public static string btnSkladisti {
            get {
                return ResourceManager.GetString("btnSkladisti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IZABERI.
        /// </summary>
        public static string btnSpoji {
            get {
                return ResourceManager.GetString("btnSpoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UKLONI.
        /// </summary>
        public static string btnUkloni {
            get {
                return ResourceManager.GetString("btnUkloni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validacija.
        /// </summary>
        public static string btnValidacija {
            get {
                return ResourceManager.GetString("btnValidacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvori.
        /// </summary>
        public static string btnZatvori {
            get {
                return ResourceManager.GetString("btnZatvori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čeka validaciju.
        /// </summary>
        public static string Čeka_validaciju {
            get {
                return ResourceManager.GetString("Čeka validaciju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CENOVNIK.
        /// </summary>
        public static string CenovnikTxtBlock {
            get {
                return ResourceManager.GetString("CenovnikTxtBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite da obrišete lek sa nazivom.
        /// </summary>
        public static string Da_li_ste_sigurni_da_želite_da_obrišete_lek_sa_nazivom {
            get {
                return ResourceManager.GetString("Da li ste sigurni da želite da obrišete lek sa nazivom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite da obrišete opremu sa nazivom.
        /// </summary>
        public static string Da_li_ste_sigurni_da_želite_da_obrišete_opremu_sa_nazivom {
            get {
                return ResourceManager.GetString("Da li ste sigurni da želite da obrišete opremu sa nazivom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite da obrišete sastojak.
        /// </summary>
        public static string Da_li_ste_sigurni_da_želite_da_obrišete_sastojak {
            get {
                return ResourceManager.GetString("Da li ste sigurni da želite da obrišete sastojak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum i vreme:.
        /// </summary>
        public static string DatumIVremeTxtBlock {
            get {
                return ResourceManager.GetString("DatumIVremeTxtBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum:.
        /// </summary>
        public static string DatumLabel {
            get {
                return ResourceManager.GetString("DatumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinamička.
        /// </summary>
        public static string Dinamička {
            get {
                return ResourceManager.GetString("Dinamička", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinamička.
        /// </summary>
        public static string DinamickaCombo {
            get {
                return ResourceManager.GetString("DinamickaCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string DodajTxtBlock {
            get {
                return ResourceManager.GetString("DodajTxtBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje leka.
        /// </summary>
        public static string Dodavanje_leka {
            get {
                return ResourceManager.GetString("Dodavanje leka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje novog sastojka.
        /// </summary>
        public static string Dodavanje_novog_sastojka {
            get {
                return ResourceManager.GetString("Dodavanje novog sastojka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje opreme.
        /// </summary>
        public static string Dodavanje_opreme {
            get {
                return ResourceManager.GetString("Dodavanje opreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje prostorije.
        /// </summary>
        public static string Dodavanje_prostorije {
            get {
                return ResourceManager.GetString("Dodavanje prostorije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string EngleskiMenuItem {
            get {
                return ResourceManager.GetString("EngleskiMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i id-jem.
        /// </summary>
        public static string i_id_jem {
            get {
                return ResourceManager.GetString("i id-jem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i šifrom.
        /// </summary>
        public static string i_šifrom {
            get {
                return ResourceManager.GetString("i šifrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string IdDataGrid {
            get {
                return ResourceManager.GetString("IdDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        public static string IdLabel {
            get {
                return ResourceManager.GetString("IdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMACIJE.
        /// </summary>
        public static string InformacijeTabItem {
            get {
                return ResourceManager.GetString("InformacijeTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        public static string IzaberiJezikMenuItem {
            get {
                return ResourceManager.GetString("IzaberiJezikMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izbor prostorija za spajanje.
        /// </summary>
        public static string Izbor_prostorija_za_spajanje {
            get {
                return ResourceManager.GetString("Izbor prostorija za spajanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena leka.
        /// </summary>
        public static string Izmena_leka {
            get {
                return ResourceManager.GetString("Izmena leka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena opreme.
        /// </summary>
        public static string Izmena_opreme {
            get {
                return ResourceManager.GetString("Izmena opreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena prostorije.
        /// </summary>
        public static string Izmena_prostorije {
            get {
                return ResourceManager.GetString("Izmena prostorije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni.
        /// </summary>
        public static string IzmeniTxtBlock {
            get {
                return ResourceManager.GetString("IzmeniTxtBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izveštaj o količini lekova - trenutno stanje.
        /// </summary>
        public static string Izveštaj_o_količini_lekova___trenutno_stanje {
            get {
                return ResourceManager.GetString("Izveštaj o količini lekova - trenutno stanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IZVEŠTAJ.
        /// </summary>
        public static string IzvestajTxtBlock {
            get {
                return ResourceManager.GetString("IzvestajTxtBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOLIČINA.
        /// </summary>
        public static string KolicinaDataGrid {
            get {
                return ResourceManager.GetString("KolicinaDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Količina:.
        /// </summary>
        public static string KolicinaLabel {
            get {
                return ResourceManager.GetString("KolicinaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOL U MG.
        /// </summary>
        public static string KolicinaUMgDataGrid {
            get {
                return ResourceManager.GetString("KolicinaUMgDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Količina u mg:.
        /// </summary>
        public static string KolicinaUMgLabel {
            get {
                return ResourceManager.GetString("KolicinaUMgLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KRAJ.
        /// </summary>
        public static string KrajDataGrid {
            get {
                return ResourceManager.GetString("KrajDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KRAJ:.
        /// </summary>
        public static string KrajLabel {
            get {
                return ResourceManager.GetString("KrajLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVADRATURA.
        /// </summary>
        public static string KvadraturaDataGrid {
            get {
                return ResourceManager.GetString("KvadraturaDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvadratura:.
        /// </summary>
        public static string KvadraturaLabel {
            get {
                return ResourceManager.GetString("KvadraturaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vroj slobodnih kreveta:.
        /// </summary>
        public static string lblBrojSlobodnihKreveta {
            get {
                return ResourceManager.GetString("lblBrojSlobodnihKreveta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupan broj kreveta:.
        /// </summary>
        public static string lblUkBrojKreveta {
            get {
                return ResourceManager.GetString("lblUkBrojKreveta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalihe:.
        /// </summary>
        public static string lblZalihe {
            get {
                return ResourceManager.GetString("lblZalihe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEKOVI.
        /// </summary>
        public static string LekoviTabItem {
            get {
                return ResourceManager.GetString("LekoviTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izveštaj o količini lekova.
        /// </summary>
        public static string NaslovTxtBlock {
            get {
                return ResourceManager.GetString("NaslovTxtBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAZIV.
        /// </summary>
        public static string NazivDataGrid {
            get {
                return ResourceManager.GetString("NazivDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv:.
        /// </summary>
        public static string NazivLabel {
            get {
                return ResourceManager.GetString("NazivLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema filtera.
        /// </summary>
        public static string NemaFilteraCombo {
            get {
                return ResourceManager.GetString("NemaFilteraCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće izmeniti lek koji čeka validaciju!.
        /// </summary>
        public static string Nije_moguće_izmeniti_lek_koji_čeka_validaciju_ {
            get {
                return ResourceManager.GetString("Nije moguće izmeniti lek koji čeka validaciju!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće obrisati lek koji čeka validaciju!.
        /// </summary>
        public static string Nije_moguće_obrisati_lek_koji_čeka_validaciju_ {
            get {
                return ResourceManager.GetString("Nije moguće obrisati lek koji čeka validaciju!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće toliko smajiti količinu. Količina ne sme biti manja od.
        /// </summary>
        public static string Nije_moguće_toliko_smajiti_količinu__Količina_ne_sme_biti_manja_od {
            get {
                return ResourceManager.GetString("Nije moguće toliko smajiti količinu. Količina ne sme biti manja od", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nova.
        /// </summary>
        public static string nova {
            get {
                return ResourceManager.GetString("nova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obaveštenja.
        /// </summary>
        public static string Obaveštenja {
            get {
                return ResourceManager.GetString("Obaveštenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBAVEŠTENJA.
        /// </summary>
        public static string ObavestenjaTxtBlock {
            get {
                return ResourceManager.GetString("ObavestenjaTxtBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obaveštenje.
        /// </summary>
        public static string Obaveštenje {
            get {
                return ResourceManager.GetString("Obaveštenje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ako želite da vidite celo obaveštenje, potrebno je da dvokliknete na obaveštenje koje želite da pročitate:.
        /// </summary>
        public static string ObavestenjeTxtBlock {
            get {
                return ResourceManager.GetString("ObavestenjeTxtBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši.
        /// </summary>
        public static string ObrisiTxtBlock {
            get {
                return ResourceManager.GetString("ObrisiTxtBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odbijen.
        /// </summary>
        public static string Odbijen {
            get {
                return ResourceManager.GetString("Odbijen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjavi se.
        /// </summary>
        public static string OdjaviSeMenuItem {
            get {
                return ResourceManager.GetString("OdjaviSeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odobren.
        /// </summary>
        public static string Odobren {
            get {
                return ResourceManager.GetString("Odobren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operaciona sala.
        /// </summary>
        public static string Operaciona_sala {
            get {
                return ResourceManager.GetString("Operaciona sala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operaciona sala.
        /// </summary>
        public static string OperacionaSalaCombo {
            get {
                return ResourceManager.GetString("OperacionaSalaCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPIS.
        /// </summary>
        public static string OpisDataGrid {
            get {
                return ResourceManager.GetString("OpisDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPIS:.
        /// </summary>
        public static string OpisLabel {
            get {
                return ResourceManager.GetString("OpisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprema sa istom šifrom već postoji!.
        /// </summary>
        public static string Oprema_sa_istom_šifrom_već_postoji_ {
            get {
                return ResourceManager.GetString("Oprema sa istom šifrom već postoji!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPREMA.
        /// </summary>
        public static string OpremaTabItem {
            get {
                return ResourceManager.GetString("OpremaTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POČETAK.
        /// </summary>
        public static string PocetakDataGrid {
            get {
                return ResourceManager.GetString("PocetakDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POČETAK:.
        /// </summary>
        public static string PocetakLabel {
            get {
                return ResourceManager.GetString("PocetakLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podela prostorije.
        /// </summary>
        public static string Podela_prostorije {
            get {
                return ResourceManager.GetString("Podela prostorije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PODELA.
        /// </summary>
        public static string PodelaLabel {
            get {
                return ResourceManager.GetString("PodelaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite broj prostorija koje će nastati podelom:.
        /// </summary>
        public static string PodelaProstorijaTxtBlock {
            get {
                return ResourceManager.GetString("PodelaProstorijaTxtBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - trenutno stanje -.
        /// </summary>
        public static string PodnaslovTxtBlock {
            get {
                return ResourceManager.GetString("PodnaslovTxtBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PONUDE I OGLASI.
        /// </summary>
        public static string PonudeIOglasiTxtBlock {
            get {
                return ResourceManager.GetString("PonudeIOglasiTxtBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potpis upravnika:.
        /// </summary>
        public static string PotpisTxtBlock {
            get {
                return ResourceManager.GetString("PotpisTxtBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREGLED RENOVIRANJA.
        /// </summary>
        public static string PregledRenoviranjaTabItem {
            get {
                return ResourceManager.GetString("PregledRenoviranjaTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREMEŠTANJE.
        /// </summary>
        public static string PremestanjeTxtBlock {
            get {
                return ResourceManager.GetString("PremestanjeTxtBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaz leka.
        /// </summary>
        public static string Prikaz_leka {
            get {
                return ResourceManager.GetString("Prikaz leka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaz opreme.
        /// </summary>
        public static string Prikaz_opreme {
            get {
                return ResourceManager.GetString("Prikaz opreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaz prostorije.
        /// </summary>
        public static string Prikaz_prostorije {
            get {
                return ResourceManager.GetString("Prikaz prostorije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži.
        /// </summary>
        public static string PrikaziTxtBlock {
            get {
                return ResourceManager.GetString("PrikaziTxtBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string ProfilMenuItem {
            get {
                return ResourceManager.GetString("ProfilMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROIZVOĐAČ.
        /// </summary>
        public static string ProizvodjacDataGrid {
            get {
                return ResourceManager.GetString("ProizvodjacDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proizvođač:.
        /// </summary>
        public static string ProizvodjacLabel {
            get {
                return ResourceManager.GetString("ProizvodjacLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prostorija je trenutno zauzeta, ne možete je obrisati..
        /// </summary>
        public static string Prostorija_je_trenutno_zauzeta__ne_možete_je_obrisati_ {
            get {
                return ResourceManager.GetString("Prostorija je trenutno zauzeta, ne možete je obrisati.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prostorija već postoji!.
        /// </summary>
        public static string Prostorija_već_postoji_ {
            get {
                return ResourceManager.GetString("Prostorija već postoji!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROSTORIJA.
        /// </summary>
        public static string ProstorijaDataGrid {
            get {
                return ResourceManager.GetString("ProstorijaDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROSTORIJE.
        /// </summary>
        public static string ProstorijeTabItem {
            get {
                return ResourceManager.GetString("ProstorijeTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renoviranje prostorije.
        /// </summary>
        public static string Renoviranje_prostorije {
            get {
                return ResourceManager.GetString("Renoviranje prostorije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENOVIRANJE.
        /// </summary>
        public static string RenoviranjeTxtBlock {
            get {
                return ResourceManager.GetString("RenoviranjeTxtBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala za preglede.
        /// </summary>
        public static string Sala_za_preglede {
            get {
                return ResourceManager.GetString("Sala za preglede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala za preglede.
        /// </summary>
        public static string SalaZaPregledeCombo {
            get {
                return ResourceManager.GetString("SalaZaPregledeCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sastojak već postoji!.
        /// </summary>
        public static string Sastojak_već_postoji_ {
            get {
                return ResourceManager.GetString("Sastojak već postoji!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sastojci.
        /// </summary>
        public static string Sastojci {
            get {
                return ResourceManager.GetString("Sastojci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SASTOJCI.
        /// </summary>
        public static string SastojciTabItem {
            get {
                return ResourceManager.GetString("SastojciTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŠIFRA.
        /// </summary>
        public static string SifraDataGrid {
            get {
                return ResourceManager.GetString("SifraDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra:.
        /// </summary>
        public static string SifraLabel {
            get {
                return ResourceManager.GetString("SifraLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKLADIŠTA.
        /// </summary>
        public static string SkladistaTabItem {
            get {
                return ResourceManager.GetString("SkladistaTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skladištenje.
        /// </summary>
        public static string Skladištenje {
            get {
                return ResourceManager.GetString("Skladištenje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skladište:.
        /// </summary>
        public static string SladisteLabel {
            get {
                return ResourceManager.GetString("SladisteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPAJANJE.
        /// </summary>
        public static string SpajanjeLabel {
            get {
                return ResourceManager.GetString("SpajanjeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPRAT.
        /// </summary>
        public static string SpratDataGrid {
            get {
                return ResourceManager.GetString("SpratDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprat:.
        /// </summary>
        public static string SpratLabel {
            get {
                return ResourceManager.GetString("SpratLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski.
        /// </summary>
        public static string SrpskiMenuItem {
            get {
                return ResourceManager.GetString("SrpskiMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŠTAMPAJ.
        /// </summary>
        public static string StampajTxtBlock {
            get {
                return ResourceManager.GetString("StampajTxtBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statička.
        /// </summary>
        public static string Statička {
            get {
                return ResourceManager.GetString("Statička", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statička.
        /// </summary>
        public static string StatickaCombo {
            get {
                return ResourceManager.GetString("StatickaCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        public static string StatusLekaDataGrid {
            get {
                return ResourceManager.GetString("StatusLekaDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svetla tema.
        /// </summary>
        public static string Svetla_tema {
            get {
                return ResourceManager.GetString("Svetla tema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svetla tema.
        /// </summary>
        public static string SvetlaTemaMenuItem {
            get {
                return ResourceManager.GetString("SvetlaTemaMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamna tema.
        /// </summary>
        public static string Tamna_tema {
            get {
                return ResourceManager.GetString("Tamna tema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIP OPREME.
        /// </summary>
        public static string TipOpremeDataGrid {
            get {
                return ResourceManager.GetString("TipOpremeDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip opreme:.
        /// </summary>
        public static string TipOpremeLabel {
            get {
                return ResourceManager.GetString("TipOpremeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIP PROSTORIJE.
        /// </summary>
        public static string TipProstorijeDataGrid {
            get {
                return ResourceManager.GetString("TipProstorijeDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip prostorije:.
        /// </summary>
        public static string TipProstorijeLabel {
            get {
                return ResourceManager.GetString("TipProstorijeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite validnu količinu! Količina mora biti veća od 0..
        /// </summary>
        public static string Unesite_validnu_količinu__Količina_mora_biti_veća_od_0_ {
            get {
                return ResourceManager.GetString("Unesite validnu količinu! Količina mora biti veća od 0.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite validnu količinu. Količina mora biti veća od 0 i manja ili jednaka od količine opreme u magacinu..
        /// </summary>
        public static string Unesite_validnu_količinu__Količina_mora_biti_veća_od_0_i_manja_ili_jednaka_od_količine_opreme_u_magacinu_ {
            get {
                return ResourceManager.GetString("Unesite validnu količinu. Količina mora biti veća od 0 i manja ili jednaka od kol" +
                        "ičine opreme u magacinu.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite datum premeštanja:.
        /// </summary>
        public static string UnesiteDatumPremestanjaLabel {
            get {
                return ResourceManager.GetString("UnesiteDatumPremestanjaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite naziv novog sastojka:.
        /// </summary>
        public static string UnesiteNazivSastojkaLabel {
            get {
                return ResourceManager.GetString("UnesiteNazivSastojkaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos datuma premeštanja statičke opreme.
        /// </summary>
        public static string Unos_datuma_premeštanja_statičke_opreme {
            get {
                return ResourceManager.GetString("Unos datuma premeštanja statičke opreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravnik.
        /// </summary>
        public static string Upravnik {
            get {
                return ResourceManager.GetString("Upravnik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vreme:.
        /// </summary>
        public static string VremeLabel {
            get {
                return ResourceManager.GetString("VremeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAHTEVI.
        /// </summary>
        public static string ZahteviTxtBlock {
            get {
                return ResourceManager.GetString("ZahteviTxtBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAKAŽI RENOVIRANJE.
        /// </summary>
        public static string ZakaziRenoviranjeTabItem {
            get {
                return ResourceManager.GetString("ZakaziRenoviranjeTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAKAŽI.
        /// </summary>
        public static string ZakaziTxtBlock {
            get {
                return ResourceManager.GetString("ZakaziTxtBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZALIHE.
        /// </summary>
        public static string ZaliheDataGrid {
            get {
                return ResourceManager.GetString("ZaliheDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAMENE.
        /// </summary>
        public static string ZameneTabItem {
            get {
                return ResourceManager.GetString("ZameneTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAUZETA.
        /// </summary>
        public static string ZauzetaDataGrid {
            get {
                return ResourceManager.GetString("ZauzetaDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zauzeta:.
        /// </summary>
        public static string ZauzetaLabel {
            get {
                return ResourceManager.GetString("ZauzetaLabel", resourceCulture);
            }
        }
    }
}
